config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  devise_for :admins 

  resources :cars
  
  namespace :admin do
    resources :cars
  end
  
  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

 
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cars
end

app/models/car.rb
class Car < ActiveRecord::Base

	validates :brand, presence: true
	validates :name, presence: true
	validates :number, presence: true
	validates :owner, presence: true
	validates :color, presence: true
	validates :date, presence: true
	validates :negotiable, presence: true
	validates :price, presence: true
	belongs_to :admin

	
end

app/controllers/admin/cars_controller.rb
class  Admin::CarsController < AdminController
	before_action :authenticate_admin!
	def index
		@cars = Car.all
	end
	
	def new
		@admin = current_admin
		@car = Car.new
	end

	def create
		@car = Car.new(car_params)
		if @car.negotiable=="yes"
				@car.negotiable == false
		else
				@car.negotiable == true
		end
		if @car.save
			redirect_to admin_cars_path
		else
			render "new"
		end
	end

	def show
			@car = Car.find(params[:id])
	end

	def edit
		@car = Car.find(params[:id])
	end

	def update
		@car = Car.find(params[:id])
			if @car.update(car_params)
				redirect_to admin_cars_path
			else
				render "edit"
			end
	end

	def destroy
		@car = Car.find(params[:id])
		@car.destroy

		redirect_to admin_cars_path
	end

	private
	  def car_params
	    params.require(:car).permit(:name, :brand, :number, :owner, :date, :price, :negotiable, :color)
	  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_filter :authenticate_admin!

	layout 'admin'
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
  	admin_cars_path
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
	layout 'application'

	def index
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	layout 'application'

	def home
	end

	def about
	end

	def contact
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	layout 'application'
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/cars/_form.html.haml
= form_for [:admin, @car] do |f|
  / - if @car.errors.any?
  / #error_explanation
  /   %h2
  /   = pluralize(@car.errors.count, "error")
  /   %ul
  /   - @car.errors.full_messages.each do |msg|
  /     %li= msg  
  .form-group
    = f.label :brand, "Car brand"
    = f.text_field :brand, class: "form-control" 
  .form-group
    = f.label :name, "Car Name"
    = f.text_field :name, class: "form-control" 
  .form-group
    = f.label :number, "Car Number"
    = f.text_field :number, class: "form-control" 
  .form-group
    = f.label :date, "Date of registration"
    = f.date_field :date, class: "form-control" 
  .form-group
    = f.label :owner, "Owner"
    = f.text_field :owner, class: "form-control" 
  .form-group
    = f.label :color, "Car Color"
    = f.text_field :color, class: "form-control" 
  .form-group
    = f.label :price, "Car Price"
    = f.text_field :price, class: "form-control" 
  .form-group
    = f.label :negotiable, "Negotiable"
    = f.select :negotiable, ['Yes','No'], {}, {class: "form-control"}
  .form-group
    = link_to "<-Back",admin_cars_path,class: "btn btn-primary"
    = f.submit :submit, class: "btn btn-success", type: "submit" 

app/views/admin/cars/edit.html.haml
%h1 Edit.
= render "form"

app/views/admin/cars/index.html.haml
%h1 AdminCars
- if admin_signed_in?
	= link_to "Sign Out",destroy_admin_session_path,method: :destroy,class:'btn btn-danger'
= link_to "Add Car", new_admin_car_path, class:'btn btn-primary '  
%h1 List of cars
.table-responsive
	%table.table.table-striped
		%tr 
			%th Car Brand
			%th Car Name
			%th Car Number
			%th Date of Registration
			%th Owner
			%th Car Color
			%th Car Price
			%th Negotiable
			%th Show
			%th Edit
			%th Delete
		- @cars.each do |car|
			%tr 
				%td= car.brand
				%td= car.name
				%td= car.number
				%td= car.date
				%td= car.owner
				%td= car.color
				%td= car.price
				%td= car.negotiable	
				%td= link_to "Show",admin_car_path(car),class: "btn btn-info"
				%td= link_to "Edit",edit_admin_car_path(car) ,class: 'btn btn-warning'
				%td= link_to "Delete",admin_car_path(car), method: :delete, data: {confirm: "are your sure your want to delete"},class: 'btn btn-danger'

			

app/views/admin/cars/new.html.haml
%h1 Please add the car details.
= render "form"

app/views/admin/cars/show.html.haml
%h1 Car Details
.table-responsive
	%table.table.table-striped
		%tr 
			%th Car Brand
			%th Car Name
			%th Car Number
			%th Date of Registration
			%th Owner
			%th Car Color
			%th Car Price
			%th Negotiable
		%tr 
			%td= @car.brand
			%td= @car.name
			%td= @car.number
			%td= @car.date
			%td= @car.owner
			%td= @car.color
			%td= @car.price
			%td= @car.negotiable	

= link_to "<-Back",admin_cars_path,class: "btn btn-primary"

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/cars/_footer.html.haml
.navbar.navbar-inverse.navfot.navbar-fixed-bottom.fot
	.container-fluid
		%div.navbar-text
			%p Kismat Auto Repaing works
			

app/views/cars/_nav.html.haml
%nav.navbar.navbar-inverse.navfot
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#myNavbar", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Kismat Auto Repairing Work
    #myNavbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => home_path} Home
        %li
          %a{:href => cars_path} Market
        %li
          %a{:href => about_path} About Us
        %li
          %a{:href => contact_path} Contact Us

app/views/cars/index.html.haml
= render 'nav'
= render 'footer'




  	

app/views/layouts/admin.html.haml
!!!
%html
	%head
		%title Admin-Garageapp
		= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		.container-fluid
			= yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Garageapp</title>
  <%= stylesheet_link_tag    'user', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_footer.html.haml
.navbar.navbar-inverse.navfot.fot
	.container-fluid
		%div.navbar-text
			%p Kismat Auto Repaing works
			

app/views/pages/_nav.html.haml
%nav.navbar.navbar-inverse.navfot
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#myNavbar", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Kismat Auto Repairing Work
    #myNavbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => home_path} Home
        %li
          %a{:href => cars_path} Market
        %li
          %a{:href => about_path} About Us
        %li
          %a{:href => contact_path} Contact Us

app/views/pages/about.html.haml
= render 'nav'
=render 'footer'

app/views/pages/contact.html.haml
= render 'nav'
.container-fluid
.row.custom
	.col-md-6
		%h1
			Get In Touch !!
		%form.form-horizontal
			.form-group
				%label.col-sm-2.control-label{:for => "Name"} NAME
				.col-sm-10
					%input.form-control{:placeholder => "Enter your name", :type => "text", :required=>''}
			.form-group
				%label.col-sm-2.control-label{:for => "Email"} Email
				.col-sm-10
					%input.form-control{:placeholder => "Enter your Email", :type => "email",:required=>''}
			.form-group
				%label.col-sm-2.control-label{:for => "Message"} Message
				.col-sm-10
					%textarea.form-control{:placeholder => "Enter your message", :type => "text", :rows=>'3'}
			.form-group
				.col-sm-offset-2.col-sm-10
					%button.btn.btn-success{:type => "submit"} Sign in
	.col-md-6 
.row.custom
	.col-md-6
		%h1 Our Offices
	.col-md-6
.row.custom
	.col-md-6
		%h3 Mumbai, MH (India)
		%div
			%p 183, Walkeshwar Road, Navyug Niketen, Mumbai- 400006
		%div
			%p Landline: 022-23684323
		%div
			%p Mobile: +91-9969000576, +91-9820381270

	.col-md-6 
		%h3 Richmond, VA (USA)
		%div
			%p 183, Walkeshwar Road, Navyug Niketen, Mumbai- 400006
		%div
			%p Landline: 022-23684323
		%div
			%p Mobile: +91-9969000576, +91-9820381270
.row.custom
	.col-md-6 
	.col-md-6 

= render 'footer'

app/views/pages/home.html.haml
= render 'nav'
.container-fluid
	.jumbotron
		%h1 My first Bootstrap website!
		%p This page will grow as we add more and more components from Bootstrap...
	.row
		.col-md-4 industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
		.col-md-4 There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, 
		.col-md-4 There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, yThere are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, 
= render 'footer'

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>